name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 16
    - name: Check
      run: |
        yarn
        yarn lint
        yarn tsc
    - name: Create config
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
    - name: Build
      run: yarn build:prod
    - name: Deploy to staging
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SCP_HOST}}
        username: github
        port: ${{ secrets.SCP_PORT }}
        key: ${{ secrets.ID_ED25519 }}
        passphrase: ${{ secrets.ID_ED25519_PASS }}
        debug: true
        overwrite: true
        source: "dist/*"
        target: /var/www/staging.uprzejmiedonosze.net/new/

